spring:
  cloud:
    gateway:
      routes:
      - id: traveling-api
        uri: lb://traveling-api
        predicates:
         - Path=/api/traveling-api/**
         - Method= GET, POST, PUT, DELETE
        filters:
         - StripPrefix=2