spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: Content-Type
      routes:
      - id: traveling-api
        uri: lb://traveling-api
        predicates:
         - Path=/api/traveling-mexico/dao/**
         - Method= GET, POST, PUT, DELETE
        filters:
         - StripPrefix=3